import { test, expect } from '@playwright/test'
test('create, autosave, reload, duplicate and trash/restore a song', async ({ page }) => {
  await page.goto('/songs/new')
  await page.getByLabel('タイトル', { exact: true }).fill('夜のノート')
  await page.getByRole('button', { name: '作成する' }).click()
  await expect(page.getByLabel('曲のタイトル')).toHaveValue('夜のノート')
  await page.getByLabel('曲のタイトル').fill('夜明けのノート')
  await page.getByLabel('テーマ', { exact: true }).click()
  await page.reload()
  await expect(page.getByLabel('曲のタイトル')).toHaveValue('夜明けのノート')
  await page.goto('/songs')
  await page.getByLabel('夜明けのノート のメニュー').click()
  await page.getByRole('button', { name: '複製', exact: true }).click()
  await expect(page.getByRole('heading', { name: '夜明けのノート のコピー' })).toBeVisible()
  await page.getByRole('button', { name: '削除', exact: true }).click()
  await page.getByRole('button', { name: 'Trash', exact: true }).click()
  await page.getByLabel('夜明けのノート のメニュー').click()
  await page.getByRole('button', { name: '復元', exact: true }).click()
  await page.getByRole('button', { name: 'All', exact: true }).click()
  await expect(page.getByRole('heading', { name: '夜明けのノート', exact: true })).toBeVisible()
})
